---
  - hosts: all
    tasks:
#      - name: set timezone to Australia/Melbourne
#        timezone:
#          name: Australia/Melbourne
      - name: install zsh
        apt:
          name: zsh
          state: present

#      - name: install git
#        apt:
#          name: git-core
#          state: present

      - name: install ho my zsh
        shell: |
            git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
            cp ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc
    become: true
